import './globals.css';
import type { Metadata } from 'next';
import { ClerkProvider } from '@clerk/nextjs';
import { Geist, Geist_Mono } from 'next/font/google';
import { Footer } from '@/components/footer';
import { NavBar } from '@/components/navbar';
import { Toaster } from 'sonner';
import { Zap } from 'lucide-react';

const geistSans = Geist({
	variable: '--font-geist-sans',
	subsets: ['latin'],
});

const geistMono = Geist_Mono({
	variable: '--font-geist-mono',
	subsets: ['latin'],
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<ClerkProvider>
			<html lang="en">
				<body
					className={`${geistSans.variable} ${geistMono.variable} antialiased`}
				>
					<Toaster
						expand={true}
						position="top-right"
						offset={{ top: 75 }}
						mobileOffset={{ top: 75 }}
						icons={{ info: <Zap /> }}
					/>
					<NavBar />
					{children}
					<Footer />
				</body>
			</html>
		</ClerkProvider>
	);
}
